package BanqueCorba;

/**
* BanqueCorba/IBanqueRemoteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Saturday, October 28, 2017 2:33:37 PM WEST
*/

public final class IBanqueRemoteHolder implements org.omg.CORBA.portable.Streamable
{
  public BanqueCorba.IBanqueRemote value = null;

  public IBanqueRemoteHolder ()
  {
  }

  public IBanqueRemoteHolder (BanqueCorba.IBanqueRemote initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BanqueCorba.IBanqueRemoteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BanqueCorba.IBanqueRemoteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BanqueCorba.IBanqueRemoteHelper.type ();
  }

}
